### ISSUE TITLE
Connecting to external LDAP

### ISSUE THREAD

**Issue by StanTowers** [lucasdiedrich/pwm#1]
Hi,

I am a beginner with Docker and I wanted to try an existing PWM Setup LDAP connection with your Docker Image. The Problem is that, when I try to login there is an Error: 
"Error 5017
Directory unavailable. If this error occurs repeatedly please contact your help desk."

I made the following docker-compose file and opened the LDAP Ports.

version: "3"

services:
  pwm:
    image: lucasdiedrich/pwm
    restart: always
    ports:
      - 8443:8443
      - 389:389
      - 636:636
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime

Can you help me with that?

**Comment by lucasdiedrich** [comment]
Hi @StanTowers, this must be something wrong with configuration with your ldap server, 

1. Your ldap should be external, so there is no point for exposing your 389/636 ports insider the container
2. In your admin configuration its where you should configure and TEST your LDAP connection.
3. On first access you should be redirect to configurations page, where you will be setting default admin & user password, configurations as domain name, and your LDAP connection.

Thanks.

**Comment by lucasdiedrich** [comment]
If you can`t remember your admin page, please erase your .config volume, it should be recreated whenever de container is restarted. PLEASE BACKUP IT FIRST

For more help you should look in [PWM Configuration Page](https://docs.google.com/document/d/1BBHPcOUxZytrqncYFInTaY2PXgW5p1EmzwV8zcpspRg/pub).
